error_summary.py, workerfarm_v5.py
WorkerFarm for Parallel API Testing
一个基于多进程的高效 API 测试调度器，支持多 GPU 并发测试、任务超时管理、日志收集与打包。
适用于大规模 PaddlePaddle、CINN、PyTorch API 精度与性能验证场景。
✨ 功能特点
•	支持多卡多进程并发测试，自动管理 GPU 资源。
•	支持 Paddle Only、Paddle+CINN、Accuracy 测试模式。
•	任务超时自动重启 Worker，防止长时间阻塞。
•	自动收集日志并打包，方便后续分析。
•	测试中自动清理 Paddle/Torch 显存，保障长时间运行稳定性。
🚀 使用示例
python3 workerfarm.py --api_config_file=error.txt --gpus=0,1,2,3 --per_gpu_concurrency=1 --timeout=1800 --accuracy
📂 输出
•	logs/：主控日志、错误用例、超时用例记录
•	worker_logs/：每个 worker 的独立执行日志
•	result_pack_*.zip：自动打包所有日志，便于归档
📋 依赖
•	Python 3.9+
•	PaddlePaddle
•	PyTorch
=> 增加多进程启动器，增加日志结果汇总脚本

engineV2.py, run.sh
1. 新增 --gpu_ids（int 类型）、--required_memory（float 类型）参数，可显式指定可用 gpu、每进程所需显存
2. 新增 --test_cpu（bool 类型）参数，可设置 paddle 为 cpu 模式下执行多进程测试
3. 新增 validate_gpu_options，有效化 gpu 相关参数
4. 新增 check_gpu_memory，启动进程池前检查/设置每 gpu 可用显存，计算可分配工作进程数，避免资源竞争
5. 优化 init_worker_gpu，不再使用 psutil 库，优先向有更多空位的 gpu 分配新进程
6. 优化 run_test_case，执行任务前检查可用显存，轮询等待，避免 OOM
7. 调整 BATCH_SIZE 至 20000
--num_gpus 可设置为 -1，代表 **使用最多的可用 gpu**
--num_workers_per_gpu 可设置为 -1，代表每 gpu **分配最多的可用工作进程**
--gpu_ids 可设置为 "-1"，代表 **使用最多的可用 gpu**
--gpu_ids 与 --num_gpus 仅有一项为 -1 时将遵从另一个参数值
--gpu_ids 与 --num_gpus 的 gpu 数量不一致时，以 --gpu_ids 优先
参数错误不会抛出错误中断程序，而是设定为推荐值
全量测试 api_config_support2torch_1.txt，命令为：
```bash
python engineV2.py --accuracy=True --api_config_file="tester/api_config/api_config_support2torch_1.txt" --num_gpus=-1 --num_workers_per_gpu=-1 …
```
=> 【BIT】引擎修复：engineV2--支持动态工作进程数、轮询可用显存、CPU多进程测试

engineV2-README.md, engineV2.py, tester/api_config/log_writer.py
1. engineV2 新增输出 *重复配置数量* 和 *已测试配置数量* 信息
2. log_writer 新增 print_log_info 方法，测试结束后将打印日志统计信息（仅在 engineV2 gpu 数量不为 0 时支持）
3. 更新 engineV2-README，介绍新参数
=> [BIT] Update engineV2, update engineV2-README

engineV2.py, tester/api_config/log_writer.py, tester/base.py, tester/paddle_only.py, tools/error_stat.py, tools/skip_seeker.py
1. 修复 `--log_dir` 参数设置在读取 checkpoint 之后的问题
2. need_skip 新增 paddle_only 参数，使得 random api 在 paddle_only 下不再跳过、正常测试
3. 更新小工具
=> [BIT] Update engineV2: fix `--log_dir` para, support paddle_only rand test

tester/paddle_to_torch/mapping.json
以我们要支持的732个API作为基础。如果mapping.json中的映射表不在732个内，则删除。
此外：
```
"paddle.nn.functional.pad": {
"torch_api": "paddle.nn.functional.pad",
"Rule": "PadRule"
},
```
改为
```
"paddle.nn.functional.pad": {
"Rule": "PadRule"
},
```
过滤脚本：
```
import json
import collections
with open("/host_home/wanghuan29/APItest/PaddleAPITest/tester/paddle_to_torch/mapping.json", "r") as f:
api_mapping = json.load(f)
api_list = ["paddle.abs","paddle.acos","paddle.acosh","paddle.add","paddle.add_n","paddle.addmm","paddle.all","paddle.allclose","paddle.amax","paddle.amin","paddle.angle","paddle.any","paddle.arange","paddle.argmax","paddle.argmin","paddle.argsort","paddle.as_complex","paddle.as_real","paddle.as_strided","paddle.asin","paddle.asinh","paddle.assign","paddle.atan","paddle.atan2","paddle.atanh","paddle.atleast_ …
```
=> refine mapping.json

engineV2.py, run-example.sh, tester/paddle_to_torch/mapping.json, tester/paddle_to_torch/rules.py
1. 优化 engineV2 validate_gpu_options
2. 优化 mapping.json、rules.py，移除 min_input_args、_format_arg
3. 修复 paddle.std
=> [BIT] Refine

tester/accuracy.py, tester/api_config/log_writer.py, tester/base.py, tester/paddle_cinn_vs_dygraph.py, tester/paddle_only.py
1. 新增 contiguous，修复 dlpack stride 不连续的报错
2. 区分 paddle error 与 numpy error
=> [BIT] Add contiguous, fix numpy error

README.md, engineV2-README.md, engineV2.py, run-example.sh
1. 优化 engineV2，取消 num_gpus=0 时的分支，确保测试时有 gpu 可用（实际上仅删除了 ifelse 中 num_gpus=0 时的分支，并把主要代码的缩进提前）；设置 num_gpus 的默认值为 -1
2. 提前检查 validate_gpu_options 的位置，优化报错与打印信息
3. 优化 run-example.sh
4. 更新 README.md 与 engineV2-README.md
=> [BIT] Update engineV2

report/big_tensor_gpu/error_config.txt
Increment API自身要求输入张量元素只有一个,因此删除对应的API config。
=> Delete incorrect increment api config

engine.py
engine.py 增加 test_cpu 选项
engineV2.py有 test_cpu 选项，但是运行需要较大内存
=> add test_cpu option in engine.py

tester/api_config/1_not_support/not_support.txt, tester/api_config/config_analyzer.py, tester/paddle_to_torch/rules.py
=> [BIT] Fix put_along_axis、topk and move error configs

tester/api_config/config_analyzer.py, tester/base.py, tester/paddle_to_torch/rules.py
1. 格式化 rules.py, base.py
2. 修复 paddle.Tensor.unflatten numpy error
=> [BIT] Fix paddle.Tensor.unflatten, format rules.py, base.py

tester/base.py
vander 是创建的tensor，没有反向，增加配置
PaddleAPITest测试通过
=> [0-size Tensor Job2 No.102] Add 0-size Tensor support for paddle.vander

tester/base.py
添加 paddle.vision.ops.distribute_fpn_proposals 的dismiss。
由 https://github.com/PaddlePaddle/Paddle/pull/74032 引入。
=> Add dismiss for paddle.vision.ops.distribute_fpn_proposals

tester/api_config/torch_error_skip.txt
matmul 在一个配置下有torch error， 需要删除该配置：
=> Remove torch error api config

tester/base_config.yaml
为paddle.unbind添加dissmiss
相关pr：https://github.com/PaddlePaddle/Paddle/pull/74224
=> add dismiss for unbind

tester/base_config.yaml
=> paddle.tensordot的精度问题

tools/api_tracer/api_alias.py, tools/api_tracer/framework_dialect.py
1. Fix `profile_hook_step` in all subclasses of `torch.optim.Optimizer`
2. Update `api_alias.py`
=> Fix `API Tracer`

tools/api_tracer/config_serializer.py, tools/api_tracer/test_infer.py, tools/api_tracer/test_train.py
Add trunction in args and configs
=> Fix `API Tracer` about exceeding length

tools/api_tracer/test_infer.py
修改了对于3种文生图大模型的推理函数。
若需要对其他模型应用该函数，请确保该模型拥有预优化的 FP16 权重文件，或对本函数的条件判断进行修改。
=> change run_inference_test_t2i in test_infer.py
