tester/api_config/config_analyzer.py

修复 merged PR #14 中引入的常规字符串解析失败的情况，具体是寻找下一个引号从 `offset` 开始，而不是 `offset + 1`，在带有空格的字符串中这两项没有区别，但是对于没有空格的字符串 `config[offset] = '"'`，`offset + 1` 后就没有引号了

[BIT] 引擎能力补齐：fix normal str parse

---

tester/api_config/config_analyzer.py
tester/base.py

目前 `base.py/gen_paddle_input()` 与 `config_analyzer.py/get_numpy_tensor()` 的代码逻辑比较混乱，代码质量较低，各位同学解决问题的方法不一致，也会造成 mentor 的 review 困难
因此本 pr 旨在统一代码逻辑，综合各位同学的修改方法，并提出一个最终的、可通用的、鲁棒性高的解决方案，且最大程度保留原本代码逻辑
在 https://github.com/PFCCLab/PaddleAPITest/pull/17 中，@mzj104 引入了 cnt（位于 `base`）与 index （位于 `config_analyzer`），用于解决不同位置的相同 Tensor 的初始化问题，如：
```
paddle.clip(x, min=None, max=None, name=None)
paddle.Tensor.clip(Tensor([2, 2],"int32"), Tensor([1],"int32"), Tensor([1],"int32"), )
```
原有的 `check_arg()` 方法无法区分位于 `min` 或 `max` 位置的参数（见问题分析），因此引入了 index，并在后续的所有代码中仅使用 index 进行区分
在 https://github.com/PFCCLab/PaddleAPITest/pull/28 中，@cszdrg 尝试使用了 index
在 https://github.com/PFCCLab/PaddleAPITest/pull/24 中，@cszdrg 额外引入了 key（位于 `config_analyzer`），将关键字也进行传入
原有的 `check_arg()` 方法在设计上确实有缺陷，我们无法断言每个参数的 Tensor 都不一样，使用 …

【BIT】引擎能力补齐：增加 index 和 key 参数、优化代码结构、增强测试鲁棒性

---

tester/base.py

refine PR #40, 增加了一个 api 到 stochastic_behavior_apis：`paddle.nn.functional.alpha_dropout`

[BIT] 引擎补齐：refine stocastic_behavior_apis

---

report/fresh_report/test_log_paddle.index_put.txt
tester/base.py

在 https://github.com/PFCCLab/PaddleAPITest/pull/49 中有两条 paddle.index_put 被误操作，因此重新检查；
经检查发现是内核崩溃错误，尝试重新撰写处理代码后，此两条仍不通过测试，因此认定是内核问题，移至 fresh_report 中；
新的 paddle.index_put 生成代码更好，且其他配置均通过测试，测试结果如下：
修复了一个小的书写错误
修改内容: 
`base.py/_handle_indices_arg()`
用于合并处理索引参数的列表或元组（目前仅有 index_put 使用），其核心是根据输入x和值value的形状计算indices参数的填充值:
1. 首先统计indices参数匹配到的x维度数量 (matched_axis)
2. 计算索引形状的最大长度 (indices_shape_len)
3. 计算预期的输出形状 (expected)
4. 计算形状缩减量 (reduced)（输出形状会被indices中的bool类型的true值数量影响）
5. 处理每个配置项:
1. bool类型索引:
1. 计算每个索引维度需要的true值数量 true_needed
2. 调整true值数量，避免超过维度大小
3. 创建全 False 的布尔掩码
4. 随机选择位置设置为 True
5. 将生成的掩码赋给配置项
2. 整数类型索引:
1. 根据输入x的对应维度大小生成随机整数索引
2. 索引范围在 [-x_dim, x_dim) 之间

【BIT】引擎能力补齐：paddle.index_put

---

tester/base.py

根据 @yuwu46 的错误报告，依次检查，发现大部分已经正常处理并已报告 fresh_report，api 分别对应 pr：
paddle.linalg.eigh
paddle.linalg.matrix_power
paddle.linalg.norm
paddle.linalg.solve
paddle.linalg.svdvals
详见 https://github.com/PFCCLab/PaddleAPITest/pull/15
paddle.nn.functional.cross_entropy
详见 https://github.com/PFCCLab/PaddleAPITest/pull/36
paddle.index_put
详见 https://github.com/PFCCLab/PaddleAPITest/pull/54
其中 paddle.index_put 有两条尚未支持的配置，修改生成方法后，全部 paddle.index_put 通过测试：

【BIT】修复引擎能力补齐的问题：paddle.index_put

---

engineV2.py
run.sh
tester/api_config/log_writer.py

1. 修复 https://github.com/PFCCLab/PaddleAPITest/pull/141 修改后造成的 engineV2 不兼容问题（需手动调用 set_cfg ）
2. engineV2 新增 --api_config_file_pattern 参数，可合并测试所有如 `tester/api_config/api_config_paddleonly_*.txt` 的文件！

[BIT] Enhance engineV2: add --api_config_file_pattern para, fix log_writer

---

README.md
tools/move_config-README.md

******
API正确性是Paddle质量的基石，影响业务训练、推理，影响用户对Paddle的信赖。至关重要。为保障Paddle API正确性，我们开发了PaddleAPITest。
目前主要考虑的正确性问题有**3**类：
>1）API**精度**正确性；
>
>2）一些**特大**Tensor，尤其是numel超过int32上限的Tensor计算异常；
>
>3）**0-Size**（numel为0的Tensor） Tensor不支持。
PaddleAPITest主要工作思路如下：
1. 在Paddle开发Trace API机制，具体见 https://github.com/PaddlePaddle/Paddle/pull/70752 ，用于抓取API调用配置，下面是一个配置例子：
```
paddle.concat(tuple(Tensor([31376, 768],"float32"),Tensor([1, 768],"float32"),), axis=0, )
```
2. 在所有Paddle单元测试（CI）、集成测试（CE）流水线中，抓取所有Paddle API的调用配置，形成了PaddleAPITest/tester/api_config下以“api_config_CI”，“api_config_CE”开头的配置集。对以上配置集进行去重、排序、梳理得到了以“api_config_merged”开头的配置集。
3. 在 PaddleAPITest 中开发一套**引擎**，加载配置集，初始化相应Tensor，调用相应API执行前/反向测试。
4. 在 PaddleAPITest 中开发一套**转换工具**，在调用Paddle API测试的同时，等同的调用Torch API，做精度对比测试。
5. …

【BIT】修改rendme

---

tester/api_config/log_writer.py
tester/base.py

1. log_writer 直接使用 os.remove 移除临时文件会导致输出重定向失效，修改为清空文件内容
2. 优化 torch_assert_accuracy 的 msg 输出，使用 torch.set_printoptions 设置为打印100 个，效果更好：

Fix redirect error, refine error_msg print

---

tester/paddle_to_torch/mapping.json
tester/paddle_to_torch/rules.py

本次修复的是以下accuracy error配置:
`paddle.var(Tensor([],"float32"), )`
`paddle.var(Tensor([],"float32"), list[], )`
在最新版本的paddle中，对于var中为标量的情况，已符合计算实际情况，输出为`nan`，无须再编写rule，直接映射就可与torch对齐。
故删除rule，对于所有的var配置均能通过，未引入新的错误。
上述两条配置本身就属于accuracy_8.txt，无需移动。

[BIT]回测问题修复：paddle.var

---

test_pipline/README.md
tools/find_API_config.py

- find_api_config可以从error_log海量的日志中找到指定API对应的错误日志及其出错时的api_config。在PaddleAPITest进行单独的API回测时，可以方便的整理出目标API对应的错误配置和日志信息。
- 具体用法请见 ``` python find_api_config.py -h ```

Add tool  find_api_config

---

tester/accuracy.py
tester/paddle_to_torch/rules.py

- fpn 输出的type类型不一致
- vander from_dlpack 不支持负数的步长

[Accuracy diff No.151、154] Fix accuracy diff for vander fpn

---

report/0size_tensor_cpu/error_config.txt
report/0size_tensor_gpu/error_config.txt

两条配置在 torch，paddle 情况下均报错，提示参数不合法，从 tester/api_config/7_0_size/0_size_tensor_1_8_1.txt 中删除。
```python
import paddle
import numpy as np
import paddle.signal as signal
import paddle.incubate.nn.functional as F
from pathlib import Path
import inspect
import torch
import numpy
from typing import Optional, List
import paddle.nn as nn
import numpy 
x = numpy.random.randn(2, 4, 21, 0)
idx = numpy.zeros((2, 4, 21, 21)).astype(numpy.int64)
kernel_size = 4
stride = 2
padding = 2
data_format = 'NCHW'
output_size = None
name = None 
px = paddle.to_tensor(x)
pidx = paddle.to_tensor(idx)
tx = torch.tensor(x)
tidx = torch.tensor(idx)
tout = torch.nn.functional.max_unpool2d(tx, tidx, kernel_size=kernel_size, stride=stride, padding=padding, output_size=output_size)
pout = …
```

[BIT] Remove illeagal max_unpool2d config

---

tester/base.py
tester/paddle_to_torch/mapping.json

原结果梯度误差的原因是 paddle.Tensor.median 默认 mode 参数为 ‘avg’，元素个数为偶数时取中间两元素的均值，torch.Tensor.median 的行为是取中间两元素的较小值，所以需要将 mode 参数设置为 ‘min’。
回测结果：
GPU:
CPU:

[Accuracy diff No.65, 66] Fix accuracy diff for paddle.Tensor.meidan API

---

tester/paddle_to_torch/mapping.json

fix typos, `dim` -> `axis`
测试通过

[Accuracy diff No.124] Fix accuracy diff for paddle.nn.functional.log_softmax API

---

tester/paddle_to_torch/rules.py

For this failed case
```txt
paddle.prod(Tensor([3, 5],"float32"), keepdim=True, )
```
In paddle, when axis is None, and keepdim is True, it will be a tensor with an element and keep input rank
But for the torch.prod api
```
if axis is None:
result = torch.prod(x, dtype = dtype)
```
it will return a 0 dims Tensor

[Accuracy diff No.134] Fix accuracy diff for paddle.prod API

---

tester/paddle_to_torch/rules.py

显式传递 dim=-1，torch 的 log_softmax 具有默认参数 None，已经被标记废弃，并且和 paddle 默认的 -1 不一致
测试通过

[Accuracy diff No.116] Fix accuracy diff for paddle.nn.functional.ctc_loss API

---

tester/accuracy.py
tester/paddle_to_torch/rules.py

paddle cpu 时不会进行 fused_log_softmax 操作，需要手动对 logits 进行 log_softmax

[Accuracy diff No.126] Fix accuracy diff for paddle.nn.functional.rnnt_loss API

---

tester/api_config/config_analyzer.py

原来的`paddle.incubate.nn.functional.fused_rotary_position_embedding`在config_analyzer.py文件中参数不支持bfloat16类型，需要对该情况做转化。
修复后未引入新的问题，原配置和bfloat16配置均能通过paddle_only测试，
accuracy测试也可以进行，但依旧存在精度问题。

[BIT] Fix fused_rotary_position_embedding to support bfloat16

---

tester/accuracy.py
tester/base.py

问题的原因是实对称矩阵或hermitian matrix的特征向量是不唯一的，可能因为底层实现的不同导致了 paddle 和 torch 的输出不同，所以应该对 paddle.linalg.eigh 的特征向量输出做单独的精度判断：一个简单的判断办法是将 paddle 和 torch 对应输出的特征向量相除，得到的应该是  e^{i \theta} *  vec[1, 1, ..., 1]^T  ，所以判断相除所得向量的所有元素(大致)相等，以及相除所得向量每个元素的模长为1即可。
另外由于 eigh_grad 的计算依赖于前向计算得到的特征向量，因此反向计算的结果也会有差异，所以建议不测 eigh 的反向算子
回测结果：
GPU:
CPU:

[Accuracy diff No.25] Fix accuracy diff for paddle.linalg.eigh API

---

tester/accuracy.py
tester/api_config/5_accuracy/accuracy_gpu_error_grads_diff.txt

paddle.cdist为python端算子，使用paddle.empty, paddle.zeros，反向为空
复制配置到 tester/api_config/5_accuracy/accuracy_gpu_error_grads_diff.txt
PaddleAPITest 测试通过

[0-size Tensor Job2 No.5] Add 0-size Tensor support for paddle.cdist

---

engine.py
engineV2-README.md
engineV2.py
engineV3.py
run-example.sh
tester/accuracy.py
tester/base.py
tester/paddle_cinn_vs_dygraph.py
tester/paddle_only.py

1. 在V1、V2中新增atol、rtol参数
2. 更改测试类传参为**kwargs
3. 更改torch_assert_accuracy、np_assert_accuracy使用atol、rtol参数

[BIT] Support atol rtol param

---

report/ci_ce_gpu/test_history/20250319/error_log.log

paddle.rsqrt 
PaddleAPITest 测试通过，配置中测试用例只有
```
paddle.rsqrt(Tensor([32, 1],"float16"), )
```
GPU

[Accuracy diff No.53] Fix accuracy diff for paddle.rsqrt API

---

tester/paddle_to_torch/rules.py

经检查发现是 SoftmaxWithCrossEntropyRule 中的形状处理的问题
回测结果（包括 accuracy_7.txt 中的 case 和 error_config.txt 中的 case）：

[Accuracy diff No.128] Fix accuracy diff for paddle.nn.functional.softmax_with_cross_entropy API

---

tester/api_config/config_analyzer.py

输入tensor y 应限定为上三角或下三角矩阵
回测结果：
case:
CPU:
GPU:

[Accuracy diff No.23、24] Fix accuracy diff for paddle.linalg.cholesky_solve API

---

report/0size_tensor_gpu/error_api_paddleonly.txt
report/0size_tensor_gpu/error_config_paddleonly.txt

paddle.expand 在配置文件 report/0size_tensor_gpu/test_history/20250528/paddleonly/error_config.txt
测试为torch error
```
python engine.py --accuracy=True --api_config='paddle.expand(x=Tensor([1, 1, 1],"int64"), shape=Tensor([0],"int32"), )'
```

[0-size Tensor No.55] Add 0-size Tensor support for expand

---

tester/accuracy.py

Paddle 中 softmax_mask_fuse 的反向只返回 x_grad，手写的 rule 会返回 x_grad 和 mask_grad

[Accuracy diff No.97] Fix accuracy diff for paddle.incubate.softmax_mask_fuse API

---

tester/api_config/config_analyzer.py
tester/paddle_to_torch/rules.py

发现在pad的长度恰为输出维度的2倍时，paddle和torch的行为存在差异，故在rules中添加对这一情况的判断
经测试，新增的5个配置和原有的1811的配置均能正确运行
发现之前的配置没有三个参数都是tensor的情况，故需要在config_analyzer中完善对indice的初始化，当indices为bool类型时，它里面true的个数，应该等于value（第三个参数）中第一维度的长度
错误原因为，新配置中label的变量类型为int32，torch不支持这种变量类型，故在rules中实现转换
if _kwargs['target'].dtype == torch.int32:
_kwargs['target'] = _kwargs['target'].long()

[BIT] fix   nn.functional.pad    Tensor.__setitem__      nn.functional.cross_entropy

---

tester/accuracy.py
tester/base.py
tester/paddle_cinn_vs_dygraph.py
tester/paddle_gpu_performance.py
tester/paddle_only.py
tools/error_stat_0_size.py
tools/error_stat_big_tensor.py

1. 新增 paddle_error_dismiss 列表，注册需要报错放行的 paddle api 与 error message
2. 新增 should_ignore_paddle_error 函数，获取是否放行
3. 在 tester/accuracy.py、tester/paddle_cinn_vs_dygraph.py、tester/paddle_gpu_performance.py、tester/paddle_only.py 新增放行判断
1. 新增 special_accuracy_atol_rtol 列表，注册需要精度放行的 paddle api 与 atol、rtol
2. 修改 np_assert_accuracy、torch_assert_accuracy 获取放行精度
1. 修改 tools/error_stat_big_tensor.py、tools/error_stat_0_size.py 匹配测试需求
paddle.nn.functional.conv1d 在 0713 版本测试中仍有 CUDA700 报错：
其余配置无效，需修改配置，torch 报错：

[PHI] Support paddle_error_dismiss, special_accuracy_atol_rtol, modify error_stat

---

tester/accuracy.py

运行配置
```
python engineV2.py --accuracy=True --api_config='paddle.nn.functional.cross_
entropy(Tensor([1, 3],"float64"), Tensor([1, 3],"float64"), soft_label=True, axis=-1, weight=None, reduction="mean", )'
```
反向应取一项
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/cross_entropy_grad_kernel.cu

Fix cross_entropy grad config

---

tester/api_config/config_analyzer.py

与以下 PR 相同：
- https://github.com/PFCCLab/PaddleAPITest/pull/357
当输入拥有奇异矩阵时，`paddle.linalg.det` 会导致矩阵求逆错误：
虽然 https://github.com/PaddlePaddle/Paddle/pull/73751 已经解决报错问题，但反向结果仍与理论值相差较大，等待后续修复
因此在仅关注 bigtensor 的情况下，先构造输入，从随机矩阵改为非奇异矩阵，以此规避奇异问题，验证 bigtensor 是否正确；修改后，所有测试均已通过：

[PHI] Fix paddle.linalg.det input from random to non-singular

---

tester/paddle_to_torch/mapping.json

由于 pytorch 的batch_norm API 没有 use_global_stats 或 track_running_stats 参数（pytorch在class层面实现的），所以使用 training if use_global_stats is None else not use_global_stats 来替代 training 可以保证pytorch行为 与 paddle行为一致。
修改后 pytorch 行为如下
1
training = False
track_running_stats =True
使用全局
2
training = False
track_running_stats = False
不使用全局
3
training = True
track_running_stats = True
使用全局
4
training = True
track_running_stats = False
不使用全局

[Accuracy diff No.109] Fix batch_norm mapping

---

tester/paddle_to_torch/rules.py

当输入tensor的numel为0时，也应该正常调用torch.reshape函数，这样才能和paddle相对齐

[0-size Tensor Job2 No.96] fix rules of reshape

---

tester/base_config.yaml

paddle.Tensor.inverse和paddle.incubate.nn.functional.variable_length_memory_efficient_attention的paddle error dismiss，参见pr：[pr74089](https://github.com/PaddlePaddle/Paddle/pull/74089) [pr74065](https://github.com/PaddlePaddle/Paddle/pull/74065)

Add paddle error dismiss

---

tester/accuracy.py
tester/api_config/config_analyzer.py
tester/base.py

1. `bf16` 类型的 `paddle_output` 在比较时（反向传播前）被 cast 至 `fp32` ，并未转回；在后续梯度生成时，生成为 `fp32` 的梯度，再进行反向传播，与期望测试逻辑不一致；
2. `bf16` 类型 `torch_output` 在反向传播前并未 cast，梯度生成同样为 `fp32` ，但是 torch 支持 `fp32` 至 `bf16` 的梯度传播；而 paddle `fp32` 至 `bf16` 的梯度传播会报错.
`torch_assert_accuracy` 支持 `bf16` 的 Tensor 比较了，因此不再需要 cast 至 `fp32` :
1.  优化 `output` 、 `out_grads` 的比较逻辑，直接删除 cast，提取复用代码，使得测试逻辑更一致
3. 修复 `get_paddle_tensor` 的 cast 类型为 `bf16`
4. 修复 `gen_paddle_output_and_output_grad` 、 `gen_torch_output_and_output_grad` ，使得生成梯度与输出类型一致
5. 修复 `need_check_grad` 中 `paddle.assign` 测试时 `self.paddle_args` 不存在的问题
全量测试 `tester/api_config/5_accuracy/accuracy_8.txt` ，全部通过:

[PHI] Fix `bf16` in comparison and grads

---

tester/api_config/torch_error_skip.txt

1. skip掉一个概率性错误：
下图展示了nll_loss api 在 ‘mean’模式下， 3次运行中两次正确，1次错误；
具体原因为输出的结果很小，是1e-5次方量级，而最终完成的计算是一个很大的reduce， 因此累加误差容易超过期望值，造成误差报错。
但其实torch 和paddle在nll_loss上的逻辑是对齐的。且能一定概率通过说明了API的正确性，对于累计误差的不确定，可能跟很多因素有关。因此建议去掉该用例。
3. skip掉一个torch cuda 700错误：

[Skip] erroneous input configs

---

tester/api_config/config_analyzer.py
tester/base.py
tester/paddle_to_torch/mapping.json
tester/paddle_to_torch/rules.py

weight 需要满足和为一。
softmax=False 时需要按照文档要求对输入手动进行softmax操作。
因为 torch tensor 自带了 softmax，所以只paddle的输入进行 softmax操作。
PyTorch 的对应 API 不支持使用 soft_label时添加weight，需要手动实现对齐 Paddle。

[Accuracy diff No.115] support softmax=False and weight != None && soft_label==True  for cross_entropy

---

tester/base_config.yaml

1. 反向计算方式相同
paddle: Paddle/paddle/phi/kernels/gpu/lerp_grad_kernel.cu:252
torch:  pytorch/tools/autograd/derivatives.yaml:936
2. 不存在溢出情况，运算仅包含加法，乘法，也没有特殊值错误情况。
3. 测试用例有时可以通过
测试配置都牵扯到broadcast, 计算有大元素reduce操作，不同cuda配置，reduce过程中不同加和过程会引起浮点数的截断误差不同。
因此建议提升容忍度。且因为错误用例最后需要进行大张量reduce, torch参考值本身数值很大，需要提高绝对误差的最大容忍度。相对误差略提高即可。

[BIG tensor]adjust tolerance of lerp op

---

engine.py
engineV2.py
tester/api_config/log_writer.py

主要瓶颈点位于 `log_writer.py` :
1. `write_to_log()` 频繁打开关闭文件
2. `aggregate_logs()` 逐行读取写入
因此在现有框架下做最小修改:
1. 新增 `_process_file_handlers` ，进程长期持有句柄，`buffering=1` 每行写入
2. 新增 `BUFFER_SIZE` ，进行块级读取
在 5k 配置下测试 `accuracy_stable` ，进程数 21，总用时提升约 44% (18min->10min)

[PHI] Using `_process_file_handlers`, add `BUFFER_SIZE`

---

tester/paddle_to_torch/rules.py

lstsq cpu
- ~rank 返回值类型 int32 和 int64 不一致~

[Accuracy diff No.102] Fix accuracy diff for paddle.lstsq API

---

tester/api_config/torch_error_skip.txt

1. api正确性：
margin_cross_loss float16实现为全float32实现，torch拆为多个算子，计算精度采用float32,中间结果存储用float16， 误差来自大tensor reduce过程,和torch中间结果丢失的精度，提升精度后改不一致可消除。
2. 测试用例中已经有相同数据规模的测试用例，可以删除该config，该config reduce 维度过高，容易报出误差。
paddle:
/host_home/xiazichao/Paddle/paddle/phi/kernels/gpu/margin_cross_entropy_kernel.cu:19
采用数值稳定的计算方式。新版本对float16直接提升精度到f32
torch：
/host_home/xiazichao/PaddleAPITest/tester/paddle_to_torch/rules.py:3689
margin_cross_entropy -> 分为 log_softmax (float16->float32) +  nll_loss   （float16 -> float32）
pytorch/aten/src/ATen/native/LossNLL.cpp:695
-> pytorch/aten/src/ATen/native/cuda/Loss.cu:224

[BIG tensor] remove improper api config

---

tester/base_config.yaml

问题1: cuda error 700 修改D的类型为int64 已解决
问题2: paddle 与torch之间的误差，是paddle的高精度计算导致的，修改atol即可

fix_softmax

---

report/big_tensor_gpu/error_config.txt

```
[accuracy error] paddle.nn.functional.cross_entropy(Tensor([3, 2, 2, 357913942],"float16"), Tensor([3, 2, 2],"int64"), soft_label=True, label_smoothing=0.7336344401714625, axis=-1, weight=None, reduction="none", )
Not equal to tolerance rtol=0.01, atol=0.01
Tensor-likes are not close!
Mismatched elements: 12 / 12 (100.0%)
Greatest absolute difference: inf at index (0, 0, 0, 0) (up to 0.01 allowed)
Greatest relative difference: nan at index (0, 0, 0, 0) (up to 0.01 allowed)
ACTUAL: (shape=torch.Size([3, 2, 2, 1]), dtype=torch.float16)
tensor([[[[5.3867],
[5.1484]],
...
[[5.1641],
[5.1367]]]], dtype=torch.float16)
DESIRED: (shape=torch.Size([3, 2, 2, 1]), dtype=torch.float16)
tensor([[[[inf],
[inf]],
...
[[inf],
[inf]]]], dtype=torch.float16)
```

[BIG tensor] fix config for preventing torch error

---

tester/base_config.yaml

matmul 和 bilinear 的误差容忍度需要增大：
1. 正确性：均调用了封装好的cublas api，且没有其他错误。且提升精度后可以pass。而不同精度使用同一套模板函数。
2. 原因分析： matmul, bilinear 在完成矩阵乘法的时候都存在维度K的reduce， reduce过程中，cublas会根据需要采用不同配置。导致reduce过程中加法的顺序并不是相同的，比如torch , paddle可能分别采用不同长度和数目组数来做组间reduce, 这一过程会引起舍入误差。由于reduce数目巨大，绝对误差容易过大，而适当调大相对误差到0.05， 0.08 就可以避免问题。
1. paddle:
paddle/phi/kernels/impl/bilinear_kernel_impl.h:25
->cublas.GEMM
2. torch:
pytorch/aten/src/ATen/native/Linear.cpp:709
->bilinear -> _trilinear -> 自定义函数
1. paddle:
paddle/phi/kernels/impl/matmul_kernel_impl.h:505
->cublasGemmStridedBatchedEx
2. torch:
pytorch/aten/src/ATen/cuda/CUDABlas.cpp:670
-> cublasGemmStridedBatchedEx

[BIG tensor] Adjust tolerance for matmul and bilinear

---

report/big_tensor_gpu/error_config.txt
report/big_tensor_gpu/error_config_paddleonly.txt
tester/base_config.yaml

paddle.linalg.matrix_rank：用于计算输入矩阵的秩（Rank），基于NVIDIA cuSOLVER库提供的奇异值分解（SVD）实现。
例：paddle.linalg.matrix_rank(Tensor([3, 47721859, 5, 6],"float32"), None, False, )
shape`[3, 47721859, 5, 6]`中
- `[3,47721859]`是batchSize。
- `[5,6]`是单个batch。
代码核心逻辑
```
for (int i = 0; i < batchSize; ++i){
// single batch
dynload::cusolverDnCgesvdj(…)
}
```
- 单个batch的元素数超过INT32限制时报错。[Paddle显式检查报错](https://github.com/PaddlePaddle/Paddle/pull/74406)
- 耗时与batchSize成正比，对示例`[3, 47721859, 5, 6]`耗时达10h+。
- INT32限制时报错添加到paddle_error_dismiss。
- 删除耗时过长config。
Torch行为：显式报错。已添加到[torch_error_skip.txt](https://github.com/PFCCLab/PaddleAPITest/pull/492)

fix paddle.linalg.matrix_rank

---

tester/api_config/config_analyzer.py

https://docs.pytorch.org/docs/stable/generated/torch.Tensor.index_put_.html#torch.Tensor.index_put_
If accumulate is False, the behavior is undefined if indices contain duplicate elements.
修改 indices生成逻辑，确保生成对 pytorch 来讲定义完整的输入。

[Accuracy diff No.98] Fix accuracy diff for paddle.index_put API
